project_id = "ykqsavtoqrhrimvwjubz"
[functions.payments-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/payments-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/payments-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/payments-webhook/*.html" ]

[functions.log-analytics]
enabled = true
verify_jwt = true
[functions.impression]
verify_jwt = false

[functions.click]
verify_jwt = false

[functions.process-creative]
verify_jwt = false

[functions.pacing-check]
verify_jwt = false
import_map = "./functions/log-analytics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/log-analytics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/log-analytics/*.html" ]

[functions.report-csv]
enabled = true
verify_jwt = true
import_map = "./functions/report-csv/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/report-csv/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/report-csv/*.html" ]

[functions.import-events]
enabled = true
verify_jwt = true
import_map = "./functions/import-events/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/import-events/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/import-events/*.html" ]

[functions.webhook-dispatch]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-dispatch/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-dispatch/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-dispatch/*.html" ]
