[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

  # Supabase Environment Variables
  NEXT_PUBLIC_SUPABASE_URL = "https://rkonwkggxaohpmxmzmfn.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrb253a2dneGFvaHBteG16bWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTk0MDQsImV4cCI6MjA3MzA3NTQwNH0.F8dsonOXlKqViCP-"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrb253a2dneGFvaHBteG16bWZuIiwicm9zZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzQ5OTQwNCwiZXhwIjoyMDczMDc1NDA0fQ.uBSaejYhSj0HRX20KcfhHQKcDTGe6171bd-X4fFQ-b0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
