// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxouecygxfwpaogpwlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeG91ZWN5Z3hmd3Bhb2dwd2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODk3NzksImV4cCI6MjA2OTc2NTc3OX0.-SQ1eAVt0E7aff-qg2jp6ySKgaXCWPoYY31TfRLTA7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});