// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykqsavtoqrhrimvwjubz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcXNhdnRvcXJocmltdndqdWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjMyMTAsImV4cCI6MjA3MTY5OTIxMH0._CtaS4TH3v4ic0miHeVzaaZOT6n6Mk2gGaEUq4l0dN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});