name: Auto PR

on:
  push:
    branches:
      - "feature/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR into main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            This PR was automatically created for branch ${{ github.ref_name }}.
            Please review and enable auto-merge.
          draft: false
